In [2]:
import pandas as pd

In [3]:
exchange_rate = pd.read_csv("Exchange_Rate.csv")
exchange_rate.head()

                                                  Country Name;Country Code;Indicator Code;Indicator Code;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
Indonesia;IDN;Official exchange rate (LCU per US$   period average);PA.NUS.FCRF;1950.3175;2029.92...

In [4]:
exports = pd.read_csv("Exports.csv")
exports.head()

  Country Name;Country Code;Indicator Name;Indicator Code;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
0  Indonesia;IND;Exports of goods and services (%...

In [5]:
fdi = pd.read_csv("FDI.csv")
fdi.head()

                                         Country Name ;Country Code;Indicator Name;Indicator Code;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
Indonesia ;IDN;Foreign direct investment   net inflows (% of GDP);BX.KLT.DINV.WD.GD.ZS;1...

In [6]:
gdp_growth = pd.read_csv("GDP_Growth.csv")
gdp_growth.head()

  Country Name;Country Code;Indicator Name;Indicator Code;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
0  Indonesia;IDN;GDP growth (annual %);NY'GDP'MKT...
1              ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

In [7]:
imports = pd.read_csv("Imports.csv")
imports.head()

  Contry Name;Contry Code;Indicator Code;Indicator;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
0  Indonesia;IDN;Imports of goods and services (%...

In [8]:
inflation = pd.read_csv("Inflation.csv")
inflation.head()

                       Country Name;Country Code;Indicator Name;Indicator;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
Idonesia;IDN;Inflation   consumer prices (annual %);FP.CPI.TOTL.ZG;9.4...

In [9]:
population_growth = pd.read_csv("Population_Growth.csv")
population_growth.head()

  Contry name;Contry Code;Indicator Code;Indicator;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
0  Indonesia;IDN;Population growth (annual %);SP....

In [11]:
unemployment = pd.read_csv("Unemployment.csv")
unemployment.head()

                           Country Name;Country Code;Indicator Name;Indicator;1991;1992;1993;1994;1995;1996;1997;1998;1999;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;2020;2021;2022;2023;2024
Indonesia;IDN;Unemployment   total (% of total labor force) (modeled ILO e...

# Data Collection

Dataset diperoleh dari World Bank.

Variabel yang digunakan:
- Exchange Rate
- Exports
- FDI
- GDP Growth
- Imports
- Inflation
- Population Growth
- Unemployment

Negara yang digunakan adalah Indonesia.